import { previewSummary, previewTrackLabels } from './quickDownload';
import { useNcmAuth } from './NcmAuthContext';
import { useQuickDownload } from './useQuickDownload';

interface Props { open: boolean; initialUrl: string; loggedIn?: boolean; validateLogin?: () => Promise<boolean>; onClose: () => void; onUrlSaved: (url: string) => void; }
export default function NcmQuickDownloadDialog({ open, initialUrl, loggedIn: loggedInProp, validateLogin: validateLoginProp, onClose, onUrlSaved }: Props) {
  const { logged: loggedFromAuth, validateForDownload } = useNcmAuth(); const state = useQuickDownload({ open, initialUrl, loggedIn: loggedInProp ?? loggedFromAuth, validateLogin: validateLoginProp ?? validateForDownload, onClose, onUrlSaved });
  if (!open) return null;
  return <div role="dialog" aria-modal="true" aria-label="网易云快捷下载" onClick={state.close} style={{ position: 'fixed', inset: 0, zIndex: 30, display: 'grid', placeItems: 'center', padding: 16, background: 'rgba(0, 0, 0, 0.4)' }}><section onClick={(event) => event.stopPropagation()} style={{ width: 'min(560px, 100%)', maxHeight: 'calc(100vh - 32px)', overflow: 'auto', borderRadius: 12, padding: 20, background: '#fff', boxShadow: '0 16px 48px rgba(0, 0, 0, 0.22)' }}><h2 style={{ marginTop: 0 }}>解析歌单并下载未下载歌曲</h2><label style={{ display: 'grid', gap: 6 }}>歌单分享链接<input value={state.url} onChange={(event) => state.changeUrl(event.target.value)} disabled={state.parsing || state.downloading} placeholder="粘贴网易云歌单分享链接" /></label><label style={{ display: 'grid', gap: 6, marginTop: 12 }}>下载音质<select value={state.level} onChange={(event) => state.setLevel(event.target.value)} disabled={state.parsing || state.downloading}><option value="standard">标准（128k）</option><option value="higher">较高（192k）</option><option value="exhigh">极高（320k）</option><option value="lossless">无损 FLAC</option><option value="hires">Hi-Res</option></select></label><button onClick={() => void state.parsePreview()} disabled={state.parsing || state.downloading || state.url.trim().length === 0} style={{ marginTop: 12 }}>{state.parsing ? '解析中…' : '解析待下载歌曲'}</button>{state.preview && <div style={{ marginTop: 16 }}><strong>{state.preview.info.name}</strong><p>{previewSummary(state.preview.pending)}</p>{state.preview.pending.length > 0 && <ol>{previewTrackLabels(state.preview.pending).map((label, index) => <li key={state.preview!.pending[index].id}>{label}</li>)}</ol>}{state.preview.pending.length > 10 && <p>仅展示前 10 首。</p>}</div>}{state.feedback && <p role="status" style={{ color: state.downloadResult?.failures.length || state.downloadResult?.callbackFailures.length ? '#b45309' : '#333' }}>{state.feedback}</p>}{state.downloadResult && (state.downloadResult.failures.length > 0 || state.downloadResult.callbackFailures.length > 0) && <ul style={{ color: '#b45309' }}>{state.downloadResult.failures.slice(0, 10).map(({ track, error }) => <li key={`download-${track.id}`}>{track.name}：下载失败（{error}）</li>)}{state.downloadResult.callbackFailures.slice(0, 10).map(({ track, error }) => <li key={`record-${track.id}`}>{track.name}：已下载但记录失败（{error}）</li>)}</ul>}<div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 20 }}><button onClick={state.close} disabled={state.downloading}>取消</button><button onClick={() => void state.confirmDownload()} disabled={!state.preview || state.preview.pending.length === 0 || state.parsing || state.downloading}>{state.downloading ? '下载中…' : '确认下载'}</button></div></section></div>;
}
