import { useEffect, useState } from 'react';
import { saveSkillCategory } from './api';
import { matchesSkillSearch } from './filters';
import type { Skill, SkillCategory } from './types';

export default function CategoryDialog({ category, skills, onClose, onSaved, onError }: { category: SkillCategory | null; skills: Skill[]; onClose: () => void; onSaved: () => void; onError: (message: string) => void }) {
  const [name, setName] = useState(category?.name ?? ''); const [query, setQuery] = useState(''); const [selected, setSelected] = useState(() => new Set(category?.skillPaths ?? [])); const [saving, setSaving] = useState(false); const visible = skills.filter((skill) => matchesSkillSearch(skill, query));
  useEffect(() => { const closeOnEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; window.addEventListener('keydown', closeOnEscape); return () => window.removeEventListener('keydown', closeOnEscape); }, [onClose]);
  const toggle = (path: string) => setSelected((current) => { const next = new Set(current); next.has(path) ? next.delete(path) : next.add(path); return next; });
  const save = async () => { setSaving(true); try { await saveSkillCategory({ ...(category ? { id: category.id } : {}), name, skillPaths: [...selected] }); onSaved(); } catch (reason) { onError(String(reason)); } finally { setSaving(false); } };
  return <div role="dialog" aria-modal="true" aria-label={category ? '编辑分类' : '新建分类'} style={{ position: 'fixed', inset: 0, zIndex: 30, display: 'grid', placeItems: 'center', padding: 16, background: 'rgba(0,0,0,.35)' }} onClick={onClose}><div style={{ width: 'min(700px, 100%)', maxHeight: '85vh', overflow: 'auto', background: '#fff', borderRadius: 12, padding: 20 }} onClick={(event) => event.stopPropagation()}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12 }}><h3 style={{ marginTop: 0 }}>{category ? '编辑分类' : '新建分类'}</h3><button onClick={onClose}>关闭</button></div><label style={{ display: 'grid', gap: 5, marginBottom: 12 }}>分类名称<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="例如：自媒体" /></label><input aria-label="搜索分类中的 skill" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索名称、原生说明、自定义描述" style={{ width: '100%', boxSizing: 'border-box', marginBottom: 10 }} /><p style={{ color: '#666', margin: '4px 0 8px' }}>已选择 {selected.size} 个 skill；搜索不会清除已勾选内容。</p><div style={{ border: '1px solid #ddd', borderRadius: 8 }}>{visible.map((skill) => <label key={skill.path} style={{ display: 'flex', gap: 8, padding: 9, borderBottom: '1px solid #eee', cursor: 'pointer' }}><input type="checkbox" checked={selected.has(skill.path)} onChange={() => toggle(skill.path)} /><span><b>{skill.name}</b><small style={{ display: 'block', color: '#666' }}>{skill.nativeDescription}</small></span></label>)}{visible.length === 0 && <p style={{ padding: 10 }}>没有匹配的 skill。</p>}</div><div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 16 }}><button onClick={onClose}>取消</button><button disabled={saving || !name.trim()} onClick={() => void save()}>{saving ? '保存中…' : '保存分类'}</button></div></div></div>;
}
