import { useEffect, useRef, useState } from 'react';
import type { Skill, SkillCategory } from './types';

const button = { cursor: 'pointer' };
export default function SkillTable({ skills, categoryNames, onSaveDescription, onDelete }: { skills: Skill[]; categoryNames: (skill: Skill) => SkillCategory[]; onSaveDescription: (skill: Skill, description: string) => Promise<boolean>; onDelete: (skill: Skill) => Promise<void> }) {
  if (skills.length === 0) return <p>没有找到匹配的 skill。</p>;
  return <div style={{ border: '1px solid #ddd', borderRadius: 8, overflowX: 'auto' }}><div style={{ minWidth: 760 }}><div style={{ display: 'grid', gridTemplateColumns: '150px minmax(200px, 1fr) minmax(200px, 1fr) 150px 72px', gap: 8, padding: 10, fontWeight: 700, background: '#f7f7f7', borderBottom: '1px solid #ddd' }}><span>名称</span><span>原生说明</span><span>自定义描述</span><span>分类</span><span>操作</span></div>{skills.map((skill) => <div key={skill.path} style={{ display: 'grid', gridTemplateColumns: '150px minmax(200px, 1fr) minmax(200px, 1fr) 150px 72px', gap: 8, padding: 10, alignItems: 'start', borderBottom: '1px solid #eee' }}><span title={skill.path}><b>{skill.name}</b>{skill.parseError && <small style={{ display: 'block', color: '#b45309', marginTop: 4 }}>{skill.parseError}</small>}</span><span title={skill.nativeDescription} style={{ display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical', overflow: 'hidden', whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{skill.nativeDescription || '—'}</span><DescriptionEditor skill={skill} onSave={onSaveDescription} /><span style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>{categoryNames(skill).map((category) => <i key={category.id} style={{ padding: '2px 6px', borderRadius: 8, fontStyle: 'normal', fontSize: 12, background: '#eef2ff' }}>{category.name}</i>) || '—'}</span><button onClick={() => void onDelete(skill)} style={{ ...button, color: '#b00020' }}>删除</button></div>)}</div></div>;
}
function DescriptionEditor({ skill, onSave }: { skill: Skill; onSave: (skill: Skill, description: string) => Promise<boolean> }) { const [editing, setEditing] = useState(false); const [draft, setDraft] = useState(skill.customDescription); const textarea = useRef<HTMLTextAreaElement>(null); useEffect(() => { setDraft(skill.customDescription); }, [skill.customDescription]); const resize = () => { if (textarea.current) { textarea.current.style.height = 'auto'; textarea.current.style.height = `${textarea.current.scrollHeight}px`; } }; useEffect(() => { if (editing) requestAnimationFrame(() => { resize(); textarea.current?.focus(); }); }, [editing]); const finish = async () => { const saved = draft === skill.customDescription || await onSave(skill, draft); if (saved) setEditing(false); }; if (!editing) return <button aria-label={`${skill.name} 自定义描述，点击编辑`} onClick={() => setEditing(true)} style={{ width: '100%', minHeight: 36, padding: 5, border: '1px solid transparent', borderRadius: 4, background: skill.customDescription ? 'transparent' : '#f7f7f7', color: skill.customDescription ? '#222' : '#888', cursor: 'text', textAlign: 'left', whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{skill.customDescription || '点击添加自定义描述'}</button>; return <textarea ref={textarea} aria-label={`${skill.name} 自定义描述`} value={draft} onInput={resize} onChange={(event) => setDraft(event.target.value)} onBlur={() => void finish()} placeholder="添加自己的描述" rows={1} style={{ width: '100%', boxSizing: 'border-box', minHeight: 36, overflow: 'hidden', resize: 'vertical' }} />; }
