import { useMemo, useState } from 'react';
import BackToTopButton from '../../shared/ui/BackToTopButton';
import CategoryDialog from './CategoryDialog';
import { matchesSkillSearch } from './filters';
import SkillCategoryMenu, { type CategoryMenuState } from './SkillCategoryMenu';
import SkillTable from './SkillTable';
import type { Skill, SkillCategory } from './types';
import { useSkills } from './useSkills';
const button = { cursor: 'pointer' }; const tabStyle = { border: '1px solid #bfdbfe', padding: '6px 10px', background: '#eff6ff', color: '#334155', cursor: 'pointer', borderRadius: 6, fontWeight: 600 }; const activeTabStyle = { border: '1px solid #2563eb', background: '#2563eb', color: '#fff', boxShadow: '0 1px 3px rgba(37, 99, 235, .28)' };
export default function SkillManagerTool() { const { skills, categories, loading, error, setError, refresh, saveDescription, remove, removeCategory } = useSkills(); const [query, setQuery] = useState(''); const [categoryFilter, setCategoryFilter] = useState<number | null>(null); const [editingCategory, setEditingCategory] = useState<SkillCategory | null | undefined>(undefined); const [categoryMenu, setCategoryMenu] = useState<CategoryMenuState | null>(null); const shown = useMemo(() => skills.filter((skill) => matchesSkillSearch(skill, query) && (categoryFilter === null || skill.categoryIds.includes(categoryFilter))), [skills, query, categoryFilter]); const categoryNames = (skill: Skill) => categories.filter((category) => skill.categoryIds.includes(category.id)); return <section style={{ padding: 16 }}><p style={{ color: '#666', marginTop: 0 }}>扫描 <code>~/.agents</code> 下的 SKILL.md；分类与自定义描述只保存于 Toolbox，不会修改原始 skill。</p><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 12 }}><input aria-label="搜索 skill" placeholder="搜索名称、原生说明、自定义描述" value={query} onChange={(event) => setQuery(event.target.value)} /><button onClick={() => setEditingCategory(null)} style={button}>新建分类</button><button onClick={() => void refresh()} disabled={loading} style={button}>↻ 刷新</button></div><div aria-label="Skill 分类" style={{ display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap', marginBottom: 8, borderBottom: '1px solid #ddd', paddingBottom: 8 }}><button onClick={() => setCategoryFilter(null)} style={{ ...tabStyle, ...(categoryFilter === null ? activeTabStyle : {}) }}>全部</button>{categories.map((category) => <button key={category.id} onClick={() => setCategoryFilter(category.id)} onContextMenu={(event) => { event.preventDefault(); setCategoryMenu({ category, x: event.clientX, y: event.clientY }); }} title="右键可编辑或删除分类" style={{ ...tabStyle, ...(categoryFilter === category.id ? activeTabStyle : {}) }}>{category.name}</button>)}</div>{!loading && !error && <p aria-live="polite" style={{ margin: '0 0 10px', color: '#666' }}>当前显示 {shown.length} 个 skill</p>}{loading ? <p>正在扫描 skills…</p> : error ? <p role="alert" style={{ color: '#b00020' }}>{error} <button onClick={() => void refresh()}>重试</button></p> : <SkillTable skills={shown} categoryNames={categoryNames} onSaveDescription={saveDescription} onDelete={remove} />}{editingCategory !== undefined && <CategoryDialog category={editingCategory} skills={skills} onClose={() => setEditingCategory(undefined)} onSaved={() => { setEditingCategory(undefined); void refresh(); }} onError={setError} />}{categoryMenu && <SkillCategoryMenu state={categoryMenu} onClose={() => setCategoryMenu(null)} onEdit={() => { setEditingCategory(categoryMenu.category); setCategoryMenu(null); }} onDelete={() => { void removeCategory(categoryMenu.category); setCategoryMenu(null); }} />}<BackToTopButton /></section>; }
