use rusqlite::{params, Connection};
use std::collections::HashSet;
use tauri::AppHandle;

use super::types::{SkillCategory, SkillCategorySave};

pub fn open_database(app: &AppHandle) -> Result<Connection, String> {
    let conn = crate::storage::open_database(app)?;
    conn.execute_batch("CREATE TABLE IF NOT EXISTS skill_metadata (skill_path TEXT PRIMARY KEY, custom_description TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);\n         CREATE TABLE IF NOT EXISTS skill_categories (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE COLLATE NOCASE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);\n         CREATE TABLE IF NOT EXISTS skill_category_memberships (category_id INTEGER NOT NULL REFERENCES skill_categories(id) ON DELETE CASCADE, skill_path TEXT NOT NULL, PRIMARY KEY(category_id, skill_path));").map_err(|e| e.to_string())?;
    Ok(conn)
}

pub fn update_metadata(app: &AppHandle, path: &str, description: String) -> Result<(), String> { open_database(app)?.execute("INSERT INTO skill_metadata(skill_path, custom_description) VALUES (?1, ?2) ON CONFLICT(skill_path) DO UPDATE SET custom_description=excluded.custom_description, updated_at=CURRENT_TIMESTAMP", params![path, description]).map_err(|e| e.to_string())?; Ok(()) }
pub fn list_categories(app: &AppHandle) -> Result<Vec<SkillCategory>, String> { let conn = open_database(app)?; let mut statement = conn.prepare("SELECT id, name FROM skill_categories ORDER BY name COLLATE NOCASE").map_err(|e| e.to_string())?; let rows = statement.query_map([], |row| Ok((row.get::<_, i64>(0)?, row.get::<_, String>(1)?))).map_err(|e| e.to_string())?; let mut categories = vec![]; for row in rows { let (id, name) = row.map_err(|e| e.to_string())?; let mut memberships = conn.prepare("SELECT skill_path FROM skill_category_memberships WHERE category_id=?1 ORDER BY skill_path").map_err(|e| e.to_string())?; let skill_paths = memberships.query_map(params![id], |row| row.get(0)).map_err(|e| e.to_string())?.collect::<Result<Vec<String>, _>>().map_err(|e| e.to_string())?; categories.push(SkillCategory { id, name, skill_paths }); } Ok(categories) }
pub fn save_category(app: &AppHandle, category: SkillCategorySave, selected: HashSet<String>) -> Result<SkillCategory, String> { let name = category.name.trim(); if name.is_empty() { return Err("分类名称不能为空".into()); } let mut conn = open_database(app)?; let transaction = conn.transaction().map_err(|e| e.to_string())?; let id = if let Some(id) = category.id { if transaction.execute("UPDATE skill_categories SET name=?1 WHERE id=?2", params![name, id]).map_err(|e| e.to_string())? == 0 { return Err("分类不存在，请刷新后重试".into()); } id } else { transaction.execute("INSERT INTO skill_categories(name) VALUES (?1)", params![name]).map_err(|e| e.to_string())?; transaction.last_insert_rowid() }; transaction.execute("DELETE FROM skill_category_memberships WHERE category_id=?1", params![id]).map_err(|e| e.to_string())?; for path in &selected { transaction.execute("INSERT INTO skill_category_memberships(category_id, skill_path) VALUES (?1, ?2)", params![id, path]).map_err(|e| e.to_string())?; } transaction.commit().map_err(|e| e.to_string())?; Ok(SkillCategory { id, name: name.to_string(), skill_paths: selected.into_iter().collect() }) }
pub fn delete_category(app: &AppHandle, id: i64) -> Result<(), String> { open_database(app)?.execute("DELETE FROM skill_categories WHERE id=?1", params![id]).map_err(|e| e.to_string())?; Ok(()) }
pub fn delete_skill_metadata(app: &AppHandle, path: &str) -> Result<(), String> { let mut conn = open_database(app)?; let transaction = conn.transaction().map_err(|e| e.to_string())?; transaction.execute("DELETE FROM skill_category_memberships WHERE skill_path=?1", params![path]).map_err(|e| e.to_string())?; transaction.execute("DELETE FROM skill_metadata WHERE skill_path=?1", params![path]).map_err(|e| e.to_string())?; transaction.commit().map_err(|e| e.to_string())?; Ok(()) }
